# Generated by Django 6.0 on 2025-12-27 18:38

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, max_length=200, verbose_name='Название сайта')),
                ('site_description', models.TextField(blank=True, verbose_name='Описание сайта')),
                ('site_photo', models.ImageField(blank=True, help_text='Загружать JPG с размерами 1200x630px', upload_to=main.models.PathAndRename('main/preference/site_photo'), verbose_name='Фотография сайта')),
            ],
            options={
                'verbose_name': 'настройки',
                'verbose_name_plural': 'настройки',
            },
        ),
    ]
