# Generated by Django 6.0 on 2025-12-30 15:40

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'preference', 'verbose_name_plural': 'preference'},
        ),
        migrations.AlterField(
            model_name='preference',
            name='site_description',
            field=models.TextField(blank=True, verbose_name='Website description'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='site_photo',
            field=models.ImageField(blank=True, help_text='Upload JPG with dimensions 1200x630px', upload_to=main.models.PathAndRename('main/preference/site_photo'), verbose_name='Photo of the site'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='site_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website title'),
        ),
    ]
