# Generated by Django 6.0 on 2025-12-28 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_book_created_book_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_prompt',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Название иллюстрации'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автор/Авторы книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(verbose_name='Содержание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название иллюстрации'),
        ),
        migrations.CreateModel(
            name='BookLlm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=50, verbose_name='Статус')),
                ('text', models.TextField(help_text='Структурированный текст книги созданный LLM', verbose_name='Структурированный текст книги')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_texts', to='books.book', verbose_name='Book')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
