# Generated by Django 6.0 on 2025-12-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_image_image_prompt_alter_book_author_alter_book_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author/Authors of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(verbose_name='Text of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Book title'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bookllm',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bookllm',
            name='text',
            field=models.TextField(help_text='Structured text of the book created by LLM', verbose_name='Structured text of the book'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_prompt',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Illustration prompt'),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Illustration title'),
        ),
    ]
