# Generated by Django 6.0 on 2025-12-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_author_alter_book_text_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookllm',
            name='text_with_image_path',
            field=models.TextField(blank=True, help_text='Structured text of the book created by LLM with image path', verbose_name='Structured text of the book with image path'),
        ),
    ]
