# Generated by Django 6.0 on 2025-12-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookllm_text_with_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookllm',
            name='text_with_image_path',
        ),
    ]
